use AutoCareDatabase
go
--creating view from the clean data
create or alter view vw_AdmissionData as

--creating CTE(temp Table) called 'CleanData', to extract non-duplicates data 

with CleanData as(
--Selecting all the data to identify duplicates using 'Dup_No', column generated by window function
select *,
ROW_NUMBER() over(partition by MRD_No, D_O_A,D_O_D order by MRD_No) Dup_No
from [HDHI Admission data]
--order by MRD_No
)
-- selecting non-duplicates data
select *
from CleanData
where Dup_No =1 and MRD_No is not null
--order by MRD_No